# Generated by Django 5.0.3 on 2024-06-10 08:45

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import cinephile_server.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city_name', models.TextField(max_length=256)),
                ('street_name', models.TextField(max_length=256)),
                ('house_number', models.IntegerField(validators=[cinephile_server.models.check_positive])),
                ('apartment_number', models.IntegerField(blank=True, null=True, validators=[cinephile_server.models.check_positive])),
                ('body', models.TextField(blank=True, null=True, validators=[cinephile_server.models.check_body])),
            ],
            options={
                'db_table': '"api_data"."address"',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url_image', models.TextField(default=None, max_length=190000, null=True)),
                ('name', models.TextField(max_length=80)),
                ('description', models.TextField(max_length=1024)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, validators=[cinephile_server.models.check_positive, cinephile_server.models.check_rating])),
            ],
            options={
                'db_table': '"api_data"."film"',
            },
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url_image', models.TextField(default=None, max_length=190000, null=True)),
                ('name', models.TextField(max_length=80)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinephile_server.address', verbose_name='address')),
            ],
            options={
                'db_table': '"api_data"."cinema"',
            },
        ),
        migrations.CreateModel(
            name='FilmCinema',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinephile_server.cinema', verbose_name='cinema')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinephile_server.film', verbose_name='film')),
            ],
            options={
                'db_table': '"api_data"."film_to_cinema"',
                'unique_together': {('cinema', 'film')},
            },
        ),
        migrations.AddField(
            model_name='film',
            name='cinemas',
            field=models.ManyToManyField(blank=True, through='cinephile_server.FilmCinema', to='cinephile_server.cinema', verbose_name='cinemas'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='films',
            field=models.ManyToManyField(through='cinephile_server.FilmCinema', to='cinephile_server.film', verbose_name='Films'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.TimeField()),
                ('place', models.TextField(max_length=256)),
                ('film_cinema', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cinephile_server.filmcinema')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"api_data"."ticket"',
            },
        ),
    ]
