# Generated by Django 5.0.3 on 2024-04-27 11:13

import cinephile_server.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=80)),
                ('address', models.TextField(max_length=1024, validators=[cinephile_server.models.check_address_len])),
            ],
            options={
                'db_table': '"api_data"."cinema"',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=80)),
                ('description', models.TextField(max_length=1024)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, validators=[cinephile_server.models.check_positive, cinephile_server.models.check_rating])),
            ],
            options={
                'db_table': '"api_data"."film"',
            },
        ),
        migrations.CreateModel(
            name='FilmCinema',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinephile_server.cinema', verbose_name='cinema')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinephile_server.film', verbose_name='film')),
            ],
            options={
                'db_table': '"api_data"."film_to_cinema"',
                'unique_together': {('cinema', 'film')},
            },
        ),
        migrations.AddField(
            model_name='film',
            name='cinemas',
            field=models.ManyToManyField(through='cinephile_server.FilmCinema', to='cinephile_server.cinema', verbose_name='cinemas'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='films',
            field=models.ManyToManyField(through='cinephile_server.FilmCinema', to='cinephile_server.film', verbose_name='Films'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('place', models.TextField(max_length=256)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[cinephile_server.models.check_positive])),
                ('film_cinema', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cinephile_server.filmcinema')),
            ],
            options={
                'db_table': '"api_data"."ticket"',
            },
        ),
    ]
