# Generated by Django 5.0.3 on 2024-06-10 09:13

from django.db import migrations, models

import cinephile_server.models


class Migration(migrations.Migration):

    dependencies = [
        ('cinephile_server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='time',
        ),
        migrations.AddField(
            model_name='ticket',
            name='film_date',
            field=models.DateTimeField(blank=True, default=cinephile_server.models.get_datetime, null=True, validators=[cinephile_server.models.check_created]),
        ),
    ]
