# Generated by Django 5.0.3 on 2024-05-13 20:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinephile_server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
