# Generated by Django 5.0.3 on 2024-05-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinephile_server', '0002_ticket_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='url_image',
            field=models.TextField(default=None, max_length=190000, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='url_image',
            field=models.TextField(default=None, max_length=190000, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time',
            field=models.TimeField(),
        ),
    ]
