# Generated by Django 5.0.3 on 2024-06-09 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinephile_server', '0004_ticket_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
        migrations.AlterField(
            model_name='film',
            name='cinemas',
            field=models.ManyToManyField(blank=True, through='cinephile_server.FilmCinema', to='cinephile_server.cinema', verbose_name='cinemas'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='film_cinema',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cinephile_server.filmcinema'),
        ),
    ]
