on: [push]
jobs:
  container-job:
    name: Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_PORT: 5432
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        ports:
        - 5432:5432
    steps:
    - uses: actions/checkout@v2
    - name: Python installation
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Dependencies installation
      run: |
        python3 -m pip install --upgrade pip
        pip install -r tests/requirements.txt
        chmod +x tests/test.sh
    - name: Test api
      run: python3 manage.py test tests.test_api
    - name: Test models
      run: python3 manage.py test tests.test_models
    - name: Test views
      run: python3 manage.py test tests.test_views
    - name: Test forms
      run: python3 manage.py test tests.test_forms
    - name: Test booking tickets
      run: python3 manage.py test tests.test_book_tickets